### ISSUE TITLE
ghidra_install.sh is miss

### ISSUE THREAD

**Issue by g0mxxm** [clearbluejar/ghidra-python-vscode-devcontainer-skeleton#2]
Hi bro, I love this project! But I can't find the file of "ghidra_install.sh". Do I need to install ghidra by myself and then modify the setting file. Can you provide a shell template？Thanks!!!

**Comment by clearbluejar** [comment]
hey! glad you like it. ghidra_install.sh is part of another package called a devcontainer [feature](https://code.visualstudio.com/blogs/2022/09/15/dev-container-features) referenced here: https://github.com/clearbluejar/ghidra-python-vscode-devcontainer-skeleton/blob/main/.devcontainer/devcontainer.json#L64-L68



That feature is available here: https://github.com/clearbluejar/features/blob/main/src/ghidra/install.sh

**Comment by g0mxxm** [comment]
Thank you very much for your reply, I will read these documents about deployment carefully, I have benefited a lot from this project of yours.
